[INFO] [1740178781.056881895] [lamp_service]: Service "allumer_lampe" prêt.
[INFO] [1740178781.310720695] [lamp_service]: État de la lampe : ON
[INFO] [1740178790.912760157] [lamp_service]: État de la lampe : OFF
[INFO] [1740178794.680189592] [lamp_service]: État de la lampe : ON
[INFO] [1740178800.568249895] [lamp_service]: État de la lampe : OFF
[INFO] [1740178804.430953413] [lamp_service]: État de la lampe : ON
[INFO] [1740178806.702735425] [lamp_service]: État de la lampe : OFF
Traceback (most recent call last):
  File "/home/alan/ros2_ws/src/install/package_projet/lib/python3.10/site-packages/package_projet/serveur.py", line 33, in <module>
    main()
  File "/home/alan/ros2_ws/src/install/package_projet/lib/python3.10/site-packages/package_projet/serveur.py", line 28, in main
    rclpy.spin(node)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 728, in _spin_once_impl
    handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 711, in wait_for_ready_callbacks
    return next(self._cb_iter)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 612, in _wait_for_ready_callbacks
    raise ExternalShutdownException()
rclpy.executors.ExternalShutdownException
